RBE1001Lib: examples/Encoder/Encoder.ino File Reference
Encoder.ino File Reference
#include <ESP32Encoder.h>
Functions
void setup ()
void loop ()
Variables
ESP32Encoder encoder
ESP32Encoder encoder2
unsigned long encoder2lastToggled
bool encoder2Paused = false
Function Documentation
loop()
void loop ()
Definition at line 35 of file Encoder.ino.
References encoder2lastToggled, encoder2Paused, ESP32Encoder::getCount(), ESP32Encoder::pauseCount(), and ESP32Encoder::resumeCount().
setup()
void setup ()
Definition at line 11 of file Encoder.ino.
References ESP32Encoder::attachHalfQuad(), ESP32Encoder::clearCount(), encoder2lastToggled, ESP32Encoder::getCount(), ESP32Encoder::setCount(), UP, and ESP32Encoder::useInternalWeakPullResistors.
Variable Documentation
encoder
ESP32Encoder encoder
Definition at line 4 of file Encoder.ino.
encoder2
ESP32Encoder encoder2
Definition at line 5 of file Encoder.ino.
encoder2lastToggled
unsigned long encoder2lastToggled
Definition at line 8 of file Encoder.ino.
Referenced by loop(), and setup().
encoder2Paused
bool encoder2Paused = false
Definition at line 9 of file Encoder.ino.
Referenced by loop().